[[redirects]]
  from = "/"
  to = "https://script.google.com/macros/s/AKfycbzSfSjWbXp-iuyYl250otK-kS7hHJWjfvi0yQQ3zAyT/dev"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"